FROM ruby:2.6.5

# Install dependencies
RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash - && \
  apt-get update && \
  apt-get install -y postgresql-client nodejs && \
  npm install -g yarn && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app
COPY Gemfile* package.json yarn.lock /app/
RUN gem install bundler -v 2.1.4 && \
  bundle install --jobs 10

# Add the Rails app
COPY . /app
