version: '3'

volumes:
  db-data:
  es-data:
  bundle:

services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.3.1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  redis:
    image: redis:5

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
      environment:
        - ELASTICSEARCH_HOST=elasticsearch
        - REDIS_SIDEKIQ_URL=redis://redis:6379/0
        - DB_HOST=db
        - DB_USER=postgres
        - DB_PASSWORD=
        - RAILS_ENV=development
        - RAILS_MAX_THREADS=5
        - LANG=C.UTF-8
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
      volumes:
        - .:/app
        - bundle:/usr/local/bundle
      depends_on:
        - db
        - sidekiq
        - elasticsearch
      tmpfs: /app/tmp
      ports:
        - "3000:3000"
      tty: true
      stdin_open: true

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - redis
    command: bundle exec sidekiq
