FROM ruby:2.6.4

# Install dependencies
RUN apt-get update
RUN apt-get install -y postgresql-client

# Install node & yarn
RUN curl -sL https://deb.nodesource.com/setup_10.x  | bash -
RUN apt-get -y install nodejs
RUN npm install -g yarn

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn

RUN mkdir /app
WORKDIR /app
COPY Gemfile* /app/
RUN bundle install

# Install yarn packages
COPY package.json yarn.lock /app/
RUN yarn install --check-files

# Add the Rails app
COPY . /app